# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :develop do
    produce(itc_team_id: 'ZMVGFV9EUS')
    match(type: development)
    gym(configuration: 'Development') 
  end
 
  lane :release do |options|
    match
    gym(clean: true, silent: options[:silent])
  end

	slather(
  build_directory: "TestReports",
  input_format: "bah",
  scheme: "FastlanePOC",
  proj: "FastlanePOC.xcodeproj"
)
end
